# Generated by Django 4.0.6 on 2022-07-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo1', models.CharField(max_length=250, verbose_name='Titulo de contato')),
                ('subtitulo', models.CharField(max_length=250, verbose_name='Subtitulo de contato')),
                ('icone1', models.ImageField(upload_to='fotos', verbose_name='Icone do whatsapp')),
                ('whatsapp', models.CharField(max_length=250, verbose_name='Whatsapp')),
                ('icone2', models.ImageField(upload_to='fotos', verbose_name='Icone do Instagram')),
                ('instagram', models.CharField(max_length=250, verbose_name='Instagram')),
                ('icone3', models.ImageField(upload_to='fotos', verbose_name='Icone do email')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('icone4', models.ImageField(upload_to='fotos', verbose_name='Icone de localização')),
                ('localizacao', models.CharField(max_length=250, verbose_name='Localização')),
                ('titulo2', models.CharField(max_length=250, verbose_name='Mandar Mensagem')),
                ('text_button', models.CharField(max_length=50, verbose_name='Texto-Botão')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo de Portfólio')),
                ('image1', models.ImageField(upload_to='fotos', verbose_name='Imagem 1')),
                ('image2', models.ImageField(upload_to='fotos', verbose_name='Imagem 2')),
                ('image3', models.ImageField(upload_to='fotos', verbose_name='Imagem 3')),
                ('image4', models.ImageField(upload_to='fotos', verbose_name='Imagem 4')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('autor', models.CharField(max_length=50, verbose_name='Autor')),
            ],
        ),
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo de Quem Somos')),
                ('image1', models.ImageField(upload_to='fotos', verbose_name='Imagem 1')),
                ('image2', models.ImageField(upload_to='fotos', verbose_name='Imagem 2')),
                ('image3', models.ImageField(upload_to='fotos', verbose_name='Imagem 3')),
                ('descricao', models.TextField(verbose_name='Descrição de Quem Somos')),
                ('text_button', models.CharField(max_length=20, verbose_name='Texto-Botão')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250, verbose_name='Titulo de Serviços')),
                ('image1', models.ImageField(upload_to='fotos', verbose_name='Imagem 1')),
                ('image2', models.ImageField(upload_to='fotos', verbose_name='Imagem 2')),
                ('image3', models.ImageField(upload_to='fotos', verbose_name='Imagem 3')),
                ('image4', models.ImageField(upload_to='fotos', verbose_name='Imagem 4')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('text_button', models.CharField(max_length=20, verbose_name='Texto-Botão')),
            ],
        ),
        migrations.AlterField(
            model_name='inicio',
            name='descricao',
            field=models.TextField(verbose_name='Mensagem de efeito'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='image',
            field=models.ImageField(upload_to='fotos', verbose_name='Imagem inicial'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='text_button',
            field=models.CharField(max_length=20, verbose_name='Texto-Botão'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Titulo inicial'),
        ),
    ]
