# Generated by Django 4.0.6 on 2022-07-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0002_contato_portfolio_quemsomos_servicos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quemsomos',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='quemsomos',
            name='text_button',
        ),
        migrations.AlterField(
            model_name='inicio',
            name='text_button',
            field=models.CharField(max_length=50, verbose_name='Texto-Botão'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='image1',
            field=models.ImageField(upload_to='fotos', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='image2',
            field=models.ImageField(upload_to='fotos', verbose_name='Imagem'),
        ),
    ]
