# Generated by Django 4.0.6 on 2022-07-13 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0003_remove_quemsomos_image3_remove_quemsomos_text_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quemsomos',
            name='image2',
        ),
    ]
