# Generated by Django 4.0.6 on 2022-07-16 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0004_remove_quemsomos_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.CharField(max_length=12)),
                ('mensagem', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='quemsomos',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='icone1',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='icone2',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='icone3',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='icone4',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='subtitulo',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='text_button',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='titulo2',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='text_button',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image5',
            field=models.ImageField(default='SOME STRING', upload_to='fotos', verbose_name='Imagem 5'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image6',
            field=models.ImageField(default='SOME STRING', upload_to='fotos', verbose_name='Imagem 6'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='descricao1',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Descrição para decoração'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='descricao2',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Descrição para Segurança'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='descricao3',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Descrição de Logistica'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='descricao4',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Descrição de Comercialização'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='descricao5',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Descrição de Planejamento'),
        ),
        migrations.AddField(
            model_name='servicos',
            name='descricao6',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Descrição de Infraestrutura'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='descricao',
            field=models.TextField(max_length=250, verbose_name='Mensagem de efeito parte 1'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='fotos', verbose_name='Imagem da logo'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Titulo inicial parte 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='autor',
            field=models.CharField(max_length=50, verbose_name='Autor 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='comentario',
            field=models.TextField(max_length=250, verbose_name='Comentario 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(default='SOME STRING', upload_to='fotos', verbose_name='Imagem 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(default='SOME STRING', upload_to='fotos', verbose_name='Imagem 2'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(default='SOME STRING', upload_to='fotos', verbose_name='Imagem 3'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image4',
            field=models.ImageField(default='SOME STRING', upload_to='fotos', verbose_name='Imagem 4'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='descricao',
            field=models.TextField(max_length=250, verbose_name='Descrição de Quem Somos parte 1'),
        ),
    ]
