# Generated by Django 4.0.6 on 2022-07-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0005_formulario_rename_image1_quemsomos_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='inicio',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='quemsomos',
            name='descricao',
        ),
        migrations.AddField(
            model_name='inicio',
            name='descricao1',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Mensagem de efeito parte 1'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='descricao2',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Mensagem de efeito parte 2'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='titulo1',
            field=models.CharField(default='SOME STRING', max_length=250, verbose_name='Titulo inicial parte 1'),
        ),
        migrations.AddField(
            model_name='inicio',
            name='titulo2',
            field=models.CharField(default='SOME STRING', max_length=250, verbose_name='Titulo inicial parte 2'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='autor1',
            field=models.CharField(default='SOME STRING', max_length=50, verbose_name='Autor 1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='autor2',
            field=models.CharField(default='SOME STRING', max_length=50, verbose_name='Autor 1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='comentario1',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Comentario 1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='comentario2',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Comentario 1'),
        ),
        migrations.AddField(
            model_name='quemsomos',
            name='descricao1',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Descrição de Quem Somos parte 1'),
        ),
        migrations.AddField(
            model_name='quemsomos',
            name='descricao2',
            field=models.TextField(default='SOME STRING', max_length=250, verbose_name='Descrição de Quem Somos parte 2'),
        ),
    ]
