# Generated by Django 4.0.6 on 2022-07-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0006_remove_inicio_descricao_remove_inicio_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='autor3',
            field=models.CharField(default='', max_length=50, verbose_name='Autor 1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='autor4',
            field=models.CharField(default='', max_length=50, verbose_name='Autor 1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='comentario3',
            field=models.TextField(default='', max_length=250, verbose_name='Comentario 1'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='comentario4',
            field=models.TextField(default='', max_length=250, verbose_name='Comentario 1'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='descricao1',
            field=models.TextField(default='', max_length=250, verbose_name='Mensagem de efeito parte 1'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='descricao2',
            field=models.TextField(default='', max_length=250, verbose_name='Mensagem de efeito parte 2'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='image',
            field=models.ImageField(default='', upload_to='fotos', verbose_name='Imagem da logo'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='titulo1',
            field=models.CharField(default='', max_length=250, verbose_name='Titulo inicial parte 1'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='titulo2',
            field=models.CharField(default='', max_length=250, verbose_name='Titulo inicial parte 2'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='autor1',
            field=models.CharField(default='', max_length=50, verbose_name='Autor 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='autor2',
            field=models.CharField(default='', max_length=50, verbose_name='Autor 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='comentario1',
            field=models.TextField(default='', max_length=250, verbose_name='Comentario 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='comentario2',
            field=models.TextField(default='', max_length=250, verbose_name='Comentario 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image1',
            field=models.ImageField(default='', upload_to='fotos', verbose_name='Imagem 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image2',
            field=models.ImageField(default='', upload_to='fotos', verbose_name='Imagem 2'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image3',
            field=models.ImageField(default='', upload_to='fotos', verbose_name='Imagem 3'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image4',
            field=models.ImageField(default='', upload_to='fotos', verbose_name='Imagem 4'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image5',
            field=models.ImageField(default='', upload_to='fotos', verbose_name='Imagem 5'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image6',
            field=models.ImageField(default='', upload_to='fotos', verbose_name='Imagem 6'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='descricao1',
            field=models.TextField(default='', max_length=250, verbose_name='Descrição de Quem Somos parte 1'),
        ),
        migrations.AlterField(
            model_name='quemsomos',
            name='descricao2',
            field=models.TextField(default='', max_length=250, verbose_name='Descrição de Quem Somos parte 2'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='descricao1',
            field=models.TextField(default='', max_length=250, verbose_name='Descrição para decoração'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='descricao2',
            field=models.TextField(default='', max_length=250, verbose_name='Descrição para Segurança'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='descricao3',
            field=models.TextField(default='', max_length=250, verbose_name='Descrição de Logistica'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='descricao4',
            field=models.TextField(default='', max_length=250, verbose_name='Descrição de Comercialização'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='descricao5',
            field=models.TextField(default='', max_length=250, verbose_name='Descrição de Planejamento'),
        ),
        migrations.AlterField(
            model_name='servicos',
            name='descricao6',
            field=models.TextField(default='', max_length=250, verbose_name='Descrição de Infraestrutura'),
        ),
    ]
