# Generated by Django 4.0.6 on 2022-07-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0007_portfolio_autor3_portfolio_autor4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='descricao1',
            field=models.TextField(default='', max_length=1000, verbose_name='Mensagem de efeito parte 1'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='descricao2',
            field=models.TextField(default='', max_length=1000, verbose_name='Mensagem de efeito parte 2'),
        ),
    ]
