# Generated by Django 4.0.6 on 2022-07-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_institucional', '0011_alter_portfolio_autor2_alter_portfolio_autor3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='autor1',
            field=models.CharField(max_length=50, verbose_name='Autor 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='autor2',
            field=models.CharField(max_length=50, verbose_name='Autor 2'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='autor3',
            field=models.CharField(max_length=50, verbose_name='Autor 3'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='autor4',
            field=models.CharField(max_length=50, verbose_name='Autor 4'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='comentario1',
            field=models.TextField(max_length=250, verbose_name='Comentario 1'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='comentario2',
            field=models.TextField(max_length=250, verbose_name='Comentario 2'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='comentario3',
            field=models.TextField(max_length=250, verbose_name='Comentario 3'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='comentario4',
            field=models.TextField(max_length=250, verbose_name='Comentario 4'),
        ),
    ]
